using System.Text;

namespace KeyboardStudio.Linux;

public sealed class XkbSymbolsGenerator : IXkbSymbolsGenerator
{
    public const string GeneratorVersion = "1.0";

    public XkbGeneratedSymbols Generate(XkbKeyboardLayout layout)
    {
        ArgumentNullException.ThrowIfNull(layout);

        var builder = new StringBuilder();
        builder.AppendLine("// Generated by KeyboardStudio. Do not edit.")
            .AppendLine("default partial alphanumeric_keys modifier_keys")
            .Append("xkb_symbols \"")
            .Append(EscapeQuoted(layout.Metadata.SectionId))
            .AppendLine("\" {")
            .Append("    name[Group1] = \"")
            .Append(EscapeQuoted(layout.Metadata.Description))
            .AppendLine("\";")
            .AppendLine();

        foreach (var mapping in layout.Mappings.OrderBy(item => item.KeyName, StringComparer.Ordinal))
        {
            builder.Append("    key ")
                .Append(mapping.KeyName)
                .AppendLine(" {")
                .Append("        type[Group1] = \"")
                .Append(XkbKeyTypeNames.Get(mapping.Type))
                .AppendLine("\",")
                .Append("        symbols[Group1] = [ ")
                .AppendJoin(", ", mapping.Keysyms)
                .AppendLine(" ]")
                .AppendLine("    };");
        }

        if (layout.UsesLevelThree)
        {
            builder.AppendLine()
                .AppendLine("    include \"level3(ralt_switch)\"");
        }

        builder.AppendLine("};");
        return new XkbGeneratedSymbols(
            Path.Combine("symbols", layout.Metadata.LayoutId),
            builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal));
    }

    private static string EscapeQuoted(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);
}
