using System.Text;

namespace KeyboardStudio.Linux;

/// <summary>Generates the app-owned symbols file containing every derived definition.</summary>
public static class XkbUserVariantSymbolsGenerator
{
    public static string Generate(IReadOnlyList<XkbUserVariantLayout> layouts)
    {
        ArgumentNullException.ThrowIfNull(layouts);

        var builder = new StringBuilder()
            .AppendLine("// Generated by KeyboardStudio. Managed file; do not edit by hand.")
            .AppendLine("// KeyboardStudio user-bundle schema 1.")
            .AppendLine();

        foreach (var layout in layouts.OrderBy(
                     layout => layout.Metadata.InternalSectionId,
                     StringComparer.Ordinal))
        {
            builder.AppendLine("partial alphanumeric_keys")
                .Append("xkb_symbols \"")
                .Append(EscapeQuoted(layout.Metadata.InternalSectionId))
                .AppendLine("\" {")
                .Append("    include \"%S/")
                .Append(EscapeQuoted(layout.Metadata.BaseLayoutId))
                .Append('(')
                .Append(EscapeQuoted(layout.Metadata.ResolvedBaseSectionId))
                .AppendLine(")\"")
                .Append("    name[Group1] = \"")
                .Append(EscapeQuoted(layout.Metadata.Description))
                .AppendLine("\";");

            if (layout.Mappings.Count > 0)
            {
                builder.AppendLine();
            }

            foreach (var mapping in layout.Mappings.OrderBy(
                         mapping => mapping.KeyName,
                         StringComparer.Ordinal))
            {
                builder.Append("    key ")
                    .Append(mapping.KeyName)
                    .AppendLine(" {")
                    .Append("        type[Group1] = \"")
                    .Append(XkbKeyTypeNames.Get(mapping.Type))
                    .AppendLine("\",")
                    .Append("        symbols[Group1] = [ ")
                    .AppendJoin(", ", mapping.Keysyms)
                    .AppendLine(" ]")
                    .AppendLine("    };");
            }

            builder.AppendLine("};")
                .AppendLine();
        }

        return Normalize(builder.ToString());
    }

    private static string EscapeQuoted(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    private static string Normalize(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd() + "\n";
}
