#!/usr/bin/env bash
# Interactively picks the runner name prefix, runner count, memory limit,
# GitHub target, and registration token, generates a per-prefix docker-compose
# file (docker-compose.generated.<prefix>.yml, shaped like docker-compose.yml)
# and compose project (<prefix>-compose), and starts the stack detached.
set -euo pipefail

usage() {
    cat <<EOF
Usage: $(basename "$0") [options]

Options:
  -p, --prefix NAME   Prefix for runner container/service names (default: keyboardstudio-runner)
  -n, --count N       Number of runners to start (default: 2)
  -r, --ram SIZE      Memory limit per runner, e.g. 8gb, 4096m (default: 8gb)
  -h, --help          Show this help and exit

If --prefix / --count / --ram are not passed as flags, the script prompts for
them interactively (press Enter to accept the default shown in brackets).

Each runner's CPU limit is always set to the host's full core count
(detected via nproc) so runners can use all available CPUs.
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_TAG="localhost/keyboardstudio-runner:latest"
RUNNER_VERSION="${RUNNER_VERSION:-2.335.1}"
RUNNER_SHA256="${RUNNER_SHA256:-4ef2f25285f0ae4477f1fe1e346db76d2f3ebf03824e2ddd1973a2819bf6c8cf}"

RUNNER_PREFIX="${RUNNER_PREFIX:-keyboardstudio-runner}"
RUNNER_COUNT="${RUNNER_COUNT:-2}"
RUNNER_RAM="${RUNNER_RAM:-8gb}"
PREFIX_FROM_FLAG=false
COUNT_FROM_FLAG=false
RAM_FROM_FLAG=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        -p|--prefix)
            RUNNER_PREFIX="$2"
            PREFIX_FROM_FLAG=true
            shift 2
            ;;
        -n|--count)
            RUNNER_COUNT="$2"
            COUNT_FROM_FLAG=true
            shift 2
            ;;
        -r|--ram)
            RUNNER_RAM="$2"
            RAM_FROM_FLAG=true
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

# Prompt for prefix/count/ram unless already given on the command line, so
# non-interactive callers can still fully script this via flags.
if ! $PREFIX_FROM_FLAG; then
    read -r -p "Runner name prefix [$RUNNER_PREFIX]: " input || true
    RUNNER_PREFIX="${input:-$RUNNER_PREFIX}"
fi
if ! $COUNT_FROM_FLAG; then
    read -r -p "Number of runners [$RUNNER_COUNT]: " input || true
    RUNNER_COUNT="${input:-$RUNNER_COUNT}"
fi
if ! $RAM_FROM_FLAG; then
    read -r -p "Memory limit per runner, e.g. 8gb/4096m [$RUNNER_RAM]: " input || true
    RUNNER_RAM="${input:-$RUNNER_RAM}"
fi

if [[ -z "$RUNNER_PREFIX" ]]; then
    echo "Error: runner prefix cannot be empty." >&2
    exit 1
fi
if ! [[ "$RUNNER_COUNT" =~ ^[0-9]+$ ]] || [[ "$RUNNER_COUNT" -lt 1 ]]; then
    echo "Error: runner count must be a positive integer, got '$RUNNER_COUNT'." >&2
    exit 1
fi
if ! [[ "$RUNNER_RAM" =~ ^[0-9]+(\.[0-9]+)?[a-zA-Z]*$ ]]; then
    echo "Error: memory limit must look like a size (e.g. 8gb, 4096m), got '$RUNNER_RAM'." >&2
    exit 1
fi

# Named after the prefix so different prefixes get their own generated
# compose file and their own compose project ("instance"), instead of
# colliding on a shared file/project name when run side by side.
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.generated.${RUNNER_PREFIX}.yml"
COMPOSE_PROJECT_NAME="${RUNNER_PREFIX}-compose"

# Each runner gets a limit equal to the full host core count, so it can burst
# to use all available CPUs when nothing else on the box is competing for them.
if command -v nproc >/dev/null 2>&1; then
    RUNNER_CPUS="$(nproc)"
else
    RUNNER_CPUS=1
fi

if command -v podman >/dev/null 2>&1; then
    ENGINE=(podman)
else
    ENGINE=(docker)
fi

image_exists() {
    if [[ "${ENGINE[0]}" == "podman" ]]; then
        podman image exists "$IMAGE_TAG"
    else
        docker image inspect "$IMAGE_TAG" >/dev/null 2>&1
    fi
}

if ! image_exists; then
    echo "Image $IMAGE_TAG not found locally — building it (this can take a while)..."
    "${ENGINE[@]}" build \
        --build-arg RUNNER_VERSION="$RUNNER_VERSION" \
        --build-arg RUNNER_SHA256="$RUNNER_SHA256" \
        -t "$IMAGE_TAG" \
        "$SCRIPT_DIR"
fi

generate_compose() {
    local out="$1"
    {
        echo "# Generated by start-runners.sh — do not edit by hand, it is overwritten on"
        echo "# every run. Project=$COMPOSE_PROJECT_NAME Prefix=$RUNNER_PREFIX Count=$RUNNER_COUNT Ram=$RUNNER_RAM Cpus=$RUNNER_CPUS"
        echo "services:"
        echo "  runner-volume-init:"
        echo "    image: alpine:3.22"
        echo "    user: \"0:0\""
        echo "    command:"
        echo "      - /bin/sh"
        echo "      - -c"
        echo "      - |"
        for i in $(seq 1 "$RUNNER_COUNT"); do
            echo "        mkdir -p /runner-work-${i}/_temp /runner-work-${i}/_tool"
        done
        local dirs=""
        for i in $(seq 1 "$RUNNER_COUNT"); do
            dirs+=" /runner-work-${i}"
        done
        echo "        chown -R 10001:10001${dirs}"
        echo "        chmod -R u+rwX${dirs}"
        echo "    volumes:"
        for i in $(seq 1 "$RUNNER_COUNT"); do
            echo "      - runner-work-${i}:/runner-work-${i}"
        done
        echo "    restart: \"no\""
        echo

        for i in $(seq 1 "$RUNNER_COUNT"); do
            local name="${RUNNER_PREFIX}-${i}"
            echo "  ${name}:"
            echo "    image: $IMAGE_TAG"
            echo "    container_name: ${name}"
            echo "    restart: always"
            echo "    user: \"10001:10001\""
            echo "    depends_on:"
            echo "      runner-volume-init:"
            echo "        condition: service_completed_successfully"
            echo "    environment:"
            echo "      - REPO_URL=\${REPO_URL:?set REPO_URL before starting}"
            echo "      - RUNNER_NAME=${name}"
            echo "      - RUNNER_LABELS=self-hosted,Linux,X64,${name}"
            echo "      - RUNNER_EPHEMERAL=false"
            echo "      - RUNNER_TOKEN=\${RUNNER_TOKEN:?set RUNNER_TOKEN before starting}"
            echo "    deploy:"
            echo "      resources:"
            echo "        limits:"
            echo "          cpus: '${RUNNER_CPUS}'"
            echo "          memory: ${RUNNER_RAM}"
            echo "        reservations:"
            echo "          cpus: '0.5'"
            echo "          memory: 512mb"
            echo "    volumes:"
            echo "      - runner-work-${i}:/home/runner/actions-runner/_work"
            echo
        done

        echo "volumes:"
        for i in $(seq 1 "$RUNNER_COUNT"); do
            echo "  runner-work-${i}:"
        done
    } > "$out"
}

generate_compose "$COMPOSE_FILE"
echo "Generated $COMPOSE_FILE (project '$COMPOSE_PROJECT_NAME', $RUNNER_COUNT runner(s), prefix '$RUNNER_PREFIX', ${RUNNER_RAM} RAM, ${RUNNER_CPUS} CPUs each)."

# These runners are dedicated to KeyboardStudio, so the target is fixed rather than prompted for.
OWNER_REPO="gosluk/KeyboardStudio"
REPO_URL="https://github.com/${OWNER_REPO}"
TOKEN_ENDPOINT="repos/${OWNER_REPO}/actions/runners/registration-token"

RUNNER_TOKEN=""
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    echo "Fetching a fresh registration token via gh api ($TOKEN_ENDPOINT)..."
    RUNNER_TOKEN="$(gh api -X POST "$TOKEN_ENDPOINT" --jq .token 2>/dev/null || true)"
fi

if [[ -z "$RUNNER_TOKEN" ]]; then
    echo "Could not fetch a token automatically (gh missing/unauthenticated, or no access to $REPO_URL)."
    read -r -s -p "GitHub runner registration token: " RUNNER_TOKEN || true
    echo
    if [[ -z "$RUNNER_TOKEN" ]]; then
        echo "Error: token cannot be empty." >&2
        exit 1
    fi
fi

export REPO_URL RUNNER_TOKEN

if command -v podman-compose >/dev/null 2>&1; then
    podman-compose -p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE" up -d
else
    docker compose -p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE" up -d
fi
