using System.Text;
using KeyboardStudio.Build;
using KeyboardStudio.Core;

namespace KeyboardStudio.Windows;

public sealed class WindowsArtifactGenerator : IArtifactGenerator
{
    public Task<GeneratedArtifact> GenerateAsync(
        KeyboardProject project,
        BuildOptions options,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(project);
        cancellationToken.ThrowIfCancellationRequested();

        var model = WindowsLayoutTranslator.Translate(project);
        var source = WindowsCSourceGenerator.Generate(model, project.Metadata.Name);
        GeneratedArtifact artifact = new(new GeneratedSource(new Dictionary<string, string>
        {
            ["keyboard.c"] = source
        }));

        return Task.FromResult(artifact);
    }
}

internal sealed record WindowsMappingEntry(
    byte ScanCode,
    ModifierLayer Modifier,
    int UnicodeScalar);

internal sealed record WindowsKeyboardLayout(IReadOnlyList<WindowsMappingEntry> Entries);

internal static class WindowsLayoutTranslator
{
    public static WindowsKeyboardLayout Translate(KeyboardProject project)
    {
        var physicalKeys = project.Keyboard.Keys.ToDictionary(key => key.Id, StringComparer.Ordinal);
        var entries = new List<WindowsMappingEntry>();

        foreach (var mapping in project.Layout.Mappings.OrderBy(mapping => mapping.KeyId, StringComparer.Ordinal))
        {
            if (!physicalKeys.TryGetValue(mapping.KeyId, out var key))
            {
                continue;
            }

            foreach (var output in mapping.Outputs.OrderBy(pair => pair.Key))
            {
                if (output.Value is not CharacterOutput characterOutput || string.IsNullOrEmpty(characterOutput.Value))
                {
                    continue;
                }

                var rune = characterOutput.Value.EnumerateRunes().First();
                entries.Add(new WindowsMappingEntry((byte)key.ScanCode, output.Key, rune.Value));
            }
        }

        return new WindowsKeyboardLayout(entries);
    }
}

internal static class WindowsCSourceGenerator
{
    public static string Generate(WindowsKeyboardLayout layout, string projectName)
    {
        var builder = new StringBuilder();
        builder.AppendLine("/* Generated by KeyboardStudio. */");
        builder.AppendLine("/* Skeleton source: real KBDTABLES generation will replace this table. */");
        builder.Append("/* Project: ").Append(EscapeComment(projectName)).AppendLine(" */");
        builder.AppendLine("#include <stdint.h>");
        builder.AppendLine();
        builder.AppendLine("typedef struct KEYBOARD_STUDIO_ENTRY {");
        builder.AppendLine("    uint16_t scan_code;");
        builder.AppendLine("    uint16_t modifier;");
        builder.AppendLine("    uint32_t unicode_scalar;");
        builder.AppendLine("} KEYBOARD_STUDIO_ENTRY;");
        builder.AppendLine();
        builder.AppendLine("static const KEYBOARD_STUDIO_ENTRY g_keyboard_layout[] = {");

        foreach (var entry in layout.Entries)
        {
            builder.Append("    { 0x")
                .Append(entry.ScanCode.ToString("X2"))
                .Append(", ")
                .Append((int)entry.Modifier)
                .Append(", 0x")
                .Append(entry.UnicodeScalar.ToString("X8"))
                .AppendLine(" },");
        }

        builder.AppendLine("};");
        builder.AppendLine();
        builder.AppendLine("const void* KbdLayerDescriptor(void)");
        builder.AppendLine("{");
        builder.AppendLine("    return g_keyboard_layout;");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string EscapeComment(string value) => value.Replace("*/", "* /", StringComparison.Ordinal);
}
