using KeyboardStudio.Build;

namespace KeyboardStudio.Windows;

internal static class WindowsNativeSourceGenerator
{
    public static GeneratedSource Generate(WindowsKeyboardLayout layout, WindowsLayoutMetadata metadata)
    {
        ArgumentNullException.ThrowIfNull(layout);
        ArgumentNullException.ThrowIfNull(metadata);

        return new GeneratedSource(new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["keyboard.c"] = WindowsCSourceGenerator.Generate(layout, metadata),
            ["keyboard.def"] = GenerateDefinitionFile(),
            ["keyboard.h"] = GenerateHeader(),
            ["keyboard.rc"] = GenerateResourceScript()
        });
    }

    private static string GenerateDefinitionFile() =>
        "LIBRARY KEYBOARD\n\nEXPORTS\n    KbdLayerDescriptor @1\n";

    private static string GenerateHeader() =>
        "#pragma once\n\n#define KBD_TYPE 4\n#include <kbd.h>\n";

    private static string GenerateResourceScript() =>
        "/* Generated by KeyboardStudio. Version metadata is emitted deterministically. */\n";
}
