using System.Globalization;
using System.Text;

namespace KeyboardStudio.Windows;

internal static class WindowsCSourceGenerator
{
    public static string Generate(WindowsKeyboardLayout layout, WindowsLayoutMetadata metadata)
    {
        var builder = new StringBuilder();
        builder.AppendLine("/* Generated by KeyboardStudio. */");
        builder.Append("/* Layout ID: ").Append(EscapeComment(metadata.LayoutId)).AppendLine(" */");
        builder.Append("/* Layout name: ").Append(EscapeComment(metadata.LayoutName)).AppendLine(" */");
        builder.AppendLine("#include <windows.h>");
        builder.AppendLine("#include \"keyboard.h\"");
        builder.AppendLine();
        builder.AppendLine("#if defined(_M_IA64)");
        builder.AppendLine("#pragma section(\".data\")");
        builder.AppendLine("#define ALLOC_SECTION_LDATA __declspec(allocate(\".data\"))");
        builder.AppendLine("#else");
        builder.AppendLine("#pragma data_seg(\".data\")");
        builder.AppendLine("#define ALLOC_SECTION_LDATA");
        builder.AppendLine("#endif");
        builder.AppendLine();
        AppendScanCodeTables(builder, layout);
        AppendKeyNameTables(builder, layout);
        AppendModifierTables(builder, layout.Modifiers);
        AppendCharacterTables(builder, layout.Characters);
        AppendLayoutDescriptor(builder);
        builder.AppendLine("PKBDTABLES KbdLayerDescriptor(VOID)");
        builder.AppendLine("{");
        builder.AppendLine("    return &KbdTables;");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendLayoutDescriptor(StringBuilder builder)
    {
        builder.AppendLine("static ALLOC_SECTION_LDATA KBDTABLES KbdTables = {");
        builder.AppendLine("    &CharModifiers,");
        builder.AppendLine("    aVkToWcharTable,");
        builder.AppendLine("    NULL, /* dead keys */");
        builder.AppendLine("    aKeyNames,");
        builder.AppendLine("    aKeyNamesExt,");
        builder.AppendLine("    NULL, /* dead-key names */");
        builder.AppendLine("    ausVscToVk,");
        builder.AppendLine("    sizeof(ausVscToVk) / sizeof(ausVscToVk[0]),");
        builder.AppendLine("    aE0VscToVk,");
        builder.AppendLine("    aE1VscToVk,");
        builder.AppendLine("    MAKELONG(KEYBOARD_STUDIO_LOCALE_FLAGS, KBD_VERSION),");
        builder.AppendLine("    0, /* maximum ligature length */");
        builder.AppendLine("    0, /* ligature entry size */");
        builder.AppendLine("    NULL /* ligatures */");
        builder.AppendLine("};");
        builder.AppendLine();
    }

    private static void AppendCharacterTables(StringBuilder builder, WindowsCharacterTable characters)
    {
        var width = characters.Width;
        if (width is not 2 and not 4)
        {
            throw new ArgumentOutOfRangeException(
                nameof(characters),
                width,
                "Windows character tables must contain either two or four modifier columns.");
        }

        var tableName = $"aVkToWch{width}";
        builder.Append("static ALLOC_SECTION_LDATA VK_TO_WCHARS")
            .Append(width.ToString(CultureInfo.InvariantCulture))
            .Append(' ')
            .Append(tableName)
            .AppendLine("[] = {");

        foreach (var row in characters.Rows.OrderBy(row => row.VirtualKey))
        {
            builder.Append("    { 0x")
                .Append(((ushort)row.VirtualKey).ToString("X4", CultureInfo.InvariantCulture))
                .Append(", ")
                .Append(row.Attributes.HasFlag(WindowsCharacterAttributes.CapsLock) ? "CAPLOK" : "0");
            AppendCharacter(builder, row.Default);
            AppendCharacter(builder, row.Shift);
            if (width == 4)
            {
                AppendCharacter(builder, row.AltGr);
                AppendCharacter(builder, row.ShiftAltGr);
            }

            builder.AppendLine(" },");
        }

        builder.Append("    { 0x0000, 0")
            .Append(string.Concat(Enumerable.Repeat(", 0x0000", width)))
            .AppendLine(" }");
        builder.AppendLine("};");
        builder.AppendLine();
        builder.AppendLine("static ALLOC_SECTION_LDATA VK_TO_WCHAR_TABLE aVkToWcharTable[] = {");
        builder.Append("    { (PVK_TO_WCHARS1)")
            .Append(tableName)
            .Append(", ")
            .Append(width.ToString(CultureInfo.InvariantCulture))
            .Append(", sizeof(")
            .Append(tableName)
            .AppendLine("[0]) },");
        builder.AppendLine("    { NULL, 0, 0 }");
        builder.AppendLine("};");
        builder.AppendLine();
    }

    private static void AppendCharacter(StringBuilder builder, char? value)
    {
        builder.Append(", ");
        if (!value.HasValue)
        {
            builder.Append("WCH_NONE");
            return;
        }

        builder.Append("0x")
            .Append(((ushort)value.Value).ToString("X4", CultureInfo.InvariantCulture));
    }

    private static void AppendModifierTables(StringBuilder builder, WindowsModifierTable modifiers)
    {
        builder.AppendLine("static ALLOC_SECTION_LDATA VK_TO_BIT aVkToBits[] = {");
        builder.AppendLine("    { VK_SHIFT, KBDSHIFT },");
        builder.AppendLine("    { VK_CONTROL, KBDCTRL },");
        builder.AppendLine("    { VK_MENU, KBDALT },");
        builder.AppendLine("    { 0, 0 }");
        builder.AppendLine("};");
        builder.AppendLine();
        builder.AppendLine("static ALLOC_SECTION_LDATA MODIFIERS CharModifiers = {");
        builder.AppendLine("    aVkToBits,");
        builder.AppendLine("    7,");
        builder.AppendLine("    {");

        foreach (var state in modifiers.States.OrderBy(state => state.Bits))
        {
            builder.Append("        ");
            if (state.Number == WindowsModifierNumber.Invalid)
            {
                builder.Append("SHFT_INVALID");
            }
            else
            {
                builder.Append(((byte)state.Number).ToString(CultureInfo.InvariantCulture));
            }

            builder.Append(" /* ")
                .Append(DescribeModifierBits(state.Bits))
                .AppendLine(" */,");
        }

        builder.AppendLine("    }");
        builder.AppendLine("};");
        builder.AppendLine();
        builder.AppendLine("#define KEYBOARD_STUDIO_LOCALE_FLAGS KLLF_ALTGR");
        builder.AppendLine();
    }

    private static string DescribeModifierBits(WindowsModifierBits bits) =>
        bits == WindowsModifierBits.None ? "Default" : bits.ToString();

    private static void AppendKeyNameTables(StringBuilder builder, WindowsKeyboardLayout layout)
    {
        AppendKeyNameTable(builder, "aKeyNames", layout.KeyNames);
        AppendKeyNameTable(builder, "aKeyNamesExt", layout.ExtendedKeyNames);
    }

    private static void AppendKeyNameTable(
        StringBuilder builder,
        string tableName,
        IReadOnlyList<WindowsKeyNameMapping> mappings)
    {
        builder.Append("static ALLOC_SECTION_LDATA VSC_LPWSTR ")
            .Append(tableName)
            .AppendLine("[] = {");
        foreach (var mapping in mappings)
        {
            builder.Append("    { 0x")
                .Append(mapping.ScanCode.ToString("X2", CultureInfo.InvariantCulture))
                .Append(", L\"")
                .Append(EscapeWideString(mapping.DisplayName))
                .AppendLine("\" },");
        }

        builder.AppendLine("    { 0x00, NULL }");
        builder.AppendLine("};");
        builder.AppendLine();
    }

    private static void AppendScanCodeTables(StringBuilder builder, WindowsKeyboardLayout layout)
    {
        var primaryByScanCode = layout.VscToVkMappings.ToDictionary(mapping => mapping.ScanCode);
        var maximumScanCode = primaryByScanCode.Count == 0 ? 0 : primaryByScanCode.Keys.Max();

        builder.AppendLine("static ALLOC_SECTION_LDATA USHORT ausVscToVk[] = {");
        for (var scanCode = 0; scanCode <= maximumScanCode; scanCode++)
        {
            builder.Append("    ");
            if (primaryByScanCode.TryGetValue((byte)scanCode, out var mapping))
            {
                AppendVirtualKey(builder, mapping.VirtualKey, extended: false);
            }
            else
            {
                builder.Append("0x0000");
            }

            builder.Append(" /* 0x")
                .Append(scanCode.ToString("X2", CultureInfo.InvariantCulture))
                .AppendLine(" */,");
        }

        builder.AppendLine("};");
        builder.AppendLine();

        builder.AppendLine("static ALLOC_SECTION_LDATA VSC_VK aE0VscToVk[] = {");
        foreach (var mapping in layout.ExtendedVscToVkMappings)
        {
            builder.Append("    { 0x")
                .Append(mapping.ScanCode.ToString("X2", CultureInfo.InvariantCulture))
                .Append(", ");
            AppendVirtualKey(builder, mapping.VirtualKey, extended: true);
            builder.AppendLine(" },");
        }

        builder.AppendLine("    { 0x00, 0x0000 }");
        builder.AppendLine("};");
        builder.AppendLine();
        builder.AppendLine("static ALLOC_SECTION_LDATA VSC_VK aE1VscToVk[] = {");
        builder.AppendLine("    { 0x00, 0x0000 }");
        builder.AppendLine("};");
        builder.AppendLine();
    }

    private static void AppendVirtualKey(StringBuilder builder, WindowsVirtualKey virtualKey, bool extended)
    {
        builder.Append("0x")
            .Append(((ushort)virtualKey).ToString("X4", CultureInfo.InvariantCulture));

        if (extended || virtualKey == WindowsVirtualKey.RightShift)
        {
            builder.Append(" | KBDEXT");
        }

        if (virtualKey is >= WindowsVirtualKey.Numpad0 and <= WindowsVirtualKey.Numpad9 ||
            virtualKey == WindowsVirtualKey.NumpadDecimal)
        {
            builder.Append(" | KBDNUMPAD | KBDSPECIAL");
        }
    }

    private static string EscapeComment(string value) => value.Replace("*/", "* /", StringComparison.Ordinal);

    private static string EscapeWideString(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
}
