using System.Globalization;
using System.Text;

namespace KeyboardStudio.Windows;

internal static class WindowsCSourceGenerator
{
    public static string Generate(WindowsKeyboardLayout layout, string projectName)
    {
        var builder = new StringBuilder();
        builder.AppendLine("/* Generated by KeyboardStudio. */");
        builder.AppendLine("/* Skeleton source: real KBDTABLES generation will replace this table. */");
        builder.Append("/* Project: ").Append(EscapeComment(projectName)).AppendLine(" */");
        builder.AppendLine("#include <stdint.h>");
        builder.AppendLine();
        builder.AppendLine("typedef struct KEYBOARD_STUDIO_ENTRY {");
        builder.AppendLine("    uint16_t scan_code;");
        builder.AppendLine("    uint16_t modifier;");
        builder.AppendLine("    uint32_t unicode_scalar;");
        builder.AppendLine("} KEYBOARD_STUDIO_ENTRY;");
        builder.AppendLine();
        builder.AppendLine("static const KEYBOARD_STUDIO_ENTRY g_keyboard_layout[] = {");

        foreach (var entry in layout.Entries)
        {
            builder.Append("    { 0x")
                .Append(entry.ScanCode.ToString("X2", CultureInfo.InvariantCulture))
                .Append(", ")
                .Append(((int)entry.Modifier).ToString(CultureInfo.InvariantCulture))
                .Append(", 0x")
                .Append(entry.UnicodeScalar.ToString("X8", CultureInfo.InvariantCulture))
                .AppendLine(" },");
        }

        builder.AppendLine("};");
        builder.AppendLine();
        builder.AppendLine("const void* KbdLayerDescriptor(void)");
        builder.AppendLine("{");
        builder.AppendLine("    return g_keyboard_layout;");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string EscapeComment(string value) => value.Replace("*/", "* /", StringComparison.Ordinal);
}
