using System.Globalization;
using System.Text;

namespace KeyboardStudio.Windows;

internal static class WindowsCSourceGenerator
{
    public static string Generate(WindowsKeyboardLayout layout, WindowsLayoutMetadata metadata)
    {
        var builder = new StringBuilder();
        builder.AppendLine("/* Generated by KeyboardStudio. */");
        builder.AppendLine("/* Skeleton source: real KBDTABLES generation will replace this table. */");
        builder.Append("/* Layout ID: ").Append(EscapeComment(metadata.LayoutId)).AppendLine(" */");
        builder.Append("/* Layout name: ").Append(EscapeComment(metadata.LayoutName)).AppendLine(" */");
        builder.AppendLine("#include <stdint.h>");
        builder.AppendLine();
        builder.AppendLine("typedef struct KEYBOARD_STUDIO_CHARACTER_ROW {");
        builder.AppendLine("    uint16_t virtual_key;");
        builder.AppendLine("    uint8_t attributes;");
        builder.AppendLine("    uint32_t normal;");
        builder.AppendLine("    uint32_t shift;");
        builder.AppendLine("    uint32_t altgr;");
        builder.AppendLine("    uint32_t shift_altgr;");
        builder.AppendLine("} KEYBOARD_STUDIO_CHARACTER_ROW;");
        builder.AppendLine();
        builder.AppendLine("static const KEYBOARD_STUDIO_CHARACTER_ROW g_keyboard_layout[] = {");

        foreach (var row in layout.Characters.Rows)
        {
            builder.Append("    { 0x")
                .Append(((ushort)row.VirtualKey).ToString("X2", CultureInfo.InvariantCulture))
                .Append(", 0x")
                .Append(((byte)row.Attributes).ToString("X2", CultureInfo.InvariantCulture))
                .Append(", ");
            AppendScalar(builder, row.Default);
            builder.Append(", ");
            AppendScalar(builder, row.Shift);
            builder.Append(", ");
            AppendScalar(builder, row.AltGr);
            builder.Append(", ");
            AppendScalar(builder, row.ShiftAltGr);
            builder.AppendLine(" },");
        }

        builder.AppendLine("};");
        builder.AppendLine();
        builder.AppendLine("const void* KbdLayerDescriptor(void)");
        builder.AppendLine("{");
        builder.AppendLine("    return g_keyboard_layout;");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendScalar(StringBuilder builder, char? value)
    {
        var scalar = value.HasValue ? value.Value : uint.MaxValue;
        builder.Append("0x").Append(scalar.ToString("X8", CultureInfo.InvariantCulture));
    }

    private static string EscapeComment(string value) => value.Replace("*/", "* /", StringComparison.Ordinal);
}
