/* Generated by KeyboardStudio. */
/* Layout ID: kbd-iso */
/* Layout name: ISO Example */
#include <windows.h>
#include "keyboard.h"

#if defined(_M_IA64)
#pragma section(".data")
#define ALLOC_SECTION_LDATA __declspec(allocate(".data"))
#else
#pragma data_seg(".data")
#define ALLOC_SECTION_LDATA
#endif

static ALLOC_SECTION_LDATA USHORT ausVscToVk[] = {
    0x0000 /* 0x00 */,
    0x0000 /* 0x01 */,
    0x0000 /* 0x02 */,
    0x0000 /* 0x03 */,
    0x0000 /* 0x04 */,
    0x0000 /* 0x05 */,
    0x0000 /* 0x06 */,
    0x0000 /* 0x07 */,
    0x0000 /* 0x08 */,
    0x0000 /* 0x09 */,
    0x0000 /* 0x0A */,
    0x0000 /* 0x0B */,
    0x0000 /* 0x0C */,
    0x0000 /* 0x0D */,
    0x0000 /* 0x0E */,
    0x0000 /* 0x0F */,
    0x0000 /* 0x10 */,
    0x0000 /* 0x11 */,
    0x0000 /* 0x12 */,
    0x0000 /* 0x13 */,
    0x0000 /* 0x14 */,
    0x0000 /* 0x15 */,
    0x0000 /* 0x16 */,
    0x0000 /* 0x17 */,
    0x0000 /* 0x18 */,
    0x0000 /* 0x19 */,
    0x0000 /* 0x1A */,
    0x0000 /* 0x1B */,
    0x000D /* 0x1C */,
    0x0000 /* 0x1D */,
    0x0000 /* 0x1E */,
    0x0000 /* 0x1F */,
    0x0000 /* 0x20 */,
    0x0000 /* 0x21 */,
    0x0000 /* 0x22 */,
    0x0000 /* 0x23 */,
    0x0000 /* 0x24 */,
    0x0000 /* 0x25 */,
    0x0000 /* 0x26 */,
    0x0000 /* 0x27 */,
    0x0000 /* 0x28 */,
    0x0000 /* 0x29 */,
    0x0000 /* 0x2A */,
    0x0000 /* 0x2B */,
    0x0000 /* 0x2C */,
    0x0000 /* 0x2D */,
    0x0000 /* 0x2E */,
    0x0000 /* 0x2F */,
    0x0000 /* 0x30 */,
    0x0000 /* 0x31 */,
    0x0000 /* 0x32 */,
    0x0000 /* 0x33 */,
    0x0000 /* 0x34 */,
    0x0000 /* 0x35 */,
    0x0000 /* 0x36 */,
    0x0000 /* 0x37 */,
    0x0000 /* 0x38 */,
    0x0000 /* 0x39 */,
    0x0000 /* 0x3A */,
    0x0000 /* 0x3B */,
    0x0000 /* 0x3C */,
    0x0000 /* 0x3D */,
    0x0000 /* 0x3E */,
    0x0000 /* 0x3F */,
    0x0000 /* 0x40 */,
    0x0000 /* 0x41 */,
    0x0000 /* 0x42 */,
    0x0000 /* 0x43 */,
    0x0000 /* 0x44 */,
    0x0000 /* 0x45 */,
    0x0000 /* 0x46 */,
    0x0000 /* 0x47 */,
    0x0000 /* 0x48 */,
    0x0000 /* 0x49 */,
    0x0000 /* 0x4A */,
    0x0000 /* 0x4B */,
    0x0000 /* 0x4C */,
    0x0000 /* 0x4D */,
    0x0000 /* 0x4E */,
    0x0000 /* 0x4F */,
    0x0000 /* 0x50 */,
    0x0000 /* 0x51 */,
    0x0000 /* 0x52 */,
    0x0000 /* 0x53 */,
    0x0000 /* 0x54 */,
    0x0000 /* 0x55 */,
    0x00E2 /* 0x56 */,
};

static ALLOC_SECTION_LDATA VSC_VK aE0VscToVk[] = {
    { 0x00, 0x0000 }
};

static ALLOC_SECTION_LDATA VSC_VK aE1VscToVk[] = {
    { 0x00, 0x0000 }
};

static ALLOC_SECTION_LDATA VSC_LPWSTR aKeyNames[] = {
    { 0x1C, L"Enter" },
    { 0x00, NULL }
};

static ALLOC_SECTION_LDATA VSC_LPWSTR aKeyNamesExt[] = {
    { 0x00, NULL }
};

static ALLOC_SECTION_LDATA VK_TO_BIT aVkToBits[] = {
    { VK_SHIFT, KBDSHIFT },
    { VK_CONTROL, KBDCTRL },
    { VK_MENU, KBDALT },
    { 0, 0 }
};

static ALLOC_SECTION_LDATA MODIFIERS CharModifiers = {
    aVkToBits,
    7,
    {
        0 /* Default */,
        1 /* Shift */,
        SHFT_INVALID /* Control */,
        SHFT_INVALID /* Shift, Control */,
        SHFT_INVALID /* Alt */,
        SHFT_INVALID /* Shift, Alt */,
        2 /* Control, Alt */,
        3 /* Shift, Control, Alt */,
    }
};

#define KEYBOARD_STUDIO_LOCALE_FLAGS KLLF_ALTGR

static ALLOC_SECTION_LDATA VK_TO_WCHARS2 aVkToWch2[] = {
    { 0x00E2, 0, 0x005C, 0x007C },
    { 0x0000, 0, 0x0000, 0x0000 }
};

static ALLOC_SECTION_LDATA VK_TO_WCHAR_TABLE aVkToWcharTable[] = {
    { (PVK_TO_WCHARS1)aVkToWch2, 2, sizeof(aVkToWch2[0]) },
    { NULL, 0, 0 }
};

static ALLOC_SECTION_LDATA KBDTABLES KbdTables = {
    &CharModifiers,
    aVkToWcharTable,
    NULL, /* dead keys */
    aKeyNames,
    aKeyNamesExt,
    NULL, /* dead-key names */
    ausVscToVk,
    sizeof(ausVscToVk) / sizeof(ausVscToVk[0]),
    aE0VscToVk,
    aE1VscToVk,
    MAKELONG(KEYBOARD_STUDIO_LOCALE_FLAGS, KBD_VERSION),
    0, /* maximum ligature length */
    0, /* ligature entry size */
    NULL /* ligatures */
};

PKBDTABLES KbdLayerDescriptor(VOID)
{
    return &KbdTables;
}
