using System.Security.Cryptography;
using System.Text;

namespace KeyboardStudio.Linux;

/// <summary>Builds exact ownership-aware file operations without mutating the filesystem.</summary>
public static class XkbInstallPlanner
{
    private const string CentralPath = "symbols/keyboardstudio";
    private const string RegistryPath = "rules/evdev.xml";
    private const string CentralHeader = "// Generated by KeyboardStudio. Managed file; do not edit by hand.";

    public static XkbInstallPlanResult PlanInstall(
        XkbGeneratedUserBundle bundle,
        XkbUserVariantMetadata metadata,
        XdgDirectoryPaths paths,
        XkbInstallationManifest manifest,
        IReadOnlyList<XkbInstallFileSnapshot> currentFiles,
        DateTimeOffset verifiedAtUtc,
        string? toolVersion)
    {
        ArgumentNullException.ThrowIfNull(bundle);
        ArgumentNullException.ThrowIfNull(metadata);
        ArgumentNullException.ThrowIfNull(paths);
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentNullException.ThrowIfNull(currentFiles);

        var diagnostics = ValidateInputs(paths, manifest, currentFiles);
        if (diagnostics.Count > 0)
        {
            return Failed(diagnostics);
        }

        var existing = manifest.Installations.SingleOrDefault(installation =>
            string.Equals(
                installation.ProjectInstallationId,
                metadata.ProjectInstallationId,
                StringComparison.Ordinal));
        if (manifest.Installations.Any(installation =>
                !string.Equals(
                    installation.ProjectInstallationId,
                    metadata.ProjectInstallationId,
                    StringComparison.Ordinal) &&
                string.Equals(installation.BaseLayoutId, metadata.BaseLayoutId, StringComparison.Ordinal) &&
                string.Equals(installation.PublicVariantId, metadata.PublicVariantId, StringComparison.Ordinal)))
        {
            diagnostics.Add(new XkbDiagnostic(
                "KSP002",
                $"Another installed project already owns '{metadata.BaseLayoutId}({metadata.PublicVariantId})'."));
        }

        var stagedCentral = bundle.Find(CentralPath);
        var bridgePath = $"symbols/{metadata.BaseLayoutId}";
        var stagedBridge = bundle.Find(bridgePath);
        if (stagedCentral is null || stagedBridge is null || bundle.Find(RegistryPath) is null)
        {
            diagnostics.Add(new XkbDiagnostic("KSP001", "The generated bundle is incomplete."));
        }

        if (diagnostics.Count > 0)
        {
            return Failed(diagnostics);
        }

        var snapshots = currentFiles.ToDictionary(file => file.RelativePath, StringComparer.Ordinal);
        var central = Snapshot(snapshots, CentralPath);
        var bridge = Snapshot(snapshots, bridgePath);
        var registry = Snapshot(snapshots, RegistryPath);
        if (central.IsSymbolicLink || bridge.IsSymbolicLink || registry.IsSymbolicLink)
        {
            diagnostics.Add(new XkbDiagnostic(
                "KSP003",
                "A destination is a symbolic link; KeyboardStudio will not plan through it."));
            return Failed(diagnostics);
        }

        var stagedCentralBlock = XkbManagedBlockEditor.Read(
            stagedCentral!.Content,
            metadata.ProjectInstallationId);
        var stagedBridgeBlock = XkbManagedBlockEditor.Read(
            stagedBridge!.Content,
            metadata.ProjectInstallationId);
        if (!stagedCentralBlock.Success || !stagedBridgeBlock.Success)
        {
            diagnostics.Add(new XkbDiagnostic("KSP001", "The generated bundle has invalid ownership blocks."));
            return Failed(diagnostics);
        }

        string centralContent;
        string centralBlockHash;
        var centralCreated = !central.Exists;
        if (!central.Exists)
        {
            if (existing is not null)
            {
                diagnostics.Add(new XkbDiagnostic("KSP004", "The app-owned symbols file is missing."));
                return Failed(diagnostics);
            }

            centralContent = stagedCentral.Content;
            centralBlockHash = stagedCentralBlock.ManagedBlockSha256!;
        }
        else
        {
            var centralRecord = manifest.Files.SingleOrDefault(file =>
                string.Equals(file.RelativePath, CentralPath, StringComparison.Ordinal));
            if (!central.Content!.StartsWith(CentralHeader, StringComparison.Ordinal) ||
                centralRecord is null ||
                !string.Equals(Hash(central.Content), centralRecord.Sha256, StringComparison.Ordinal))
            {
                diagnostics.Add(new XkbDiagnostic(
                    "KSP004",
                    "symbols/keyboardstudio is unowned or was changed outside KeyboardStudio."));
                return Failed(diagnostics);
            }

            var edit = XkbManagedBlockEditor.Upsert(
                central.Content,
                metadata.ProjectInstallationId,
                metadata.InternalSectionId,
                stagedCentralBlock.Content!,
                existing?.CentralBlockSha256);
            if (!edit.Success)
            {
                return Failed(edit.Diagnostics);
            }

            centralContent = edit.Content!;
            centralBlockHash = edit.ManagedBlockSha256!;
            centralCreated = centralRecord.WasCreatedByKeyboardStudio;
        }

        var bridgeEdit = XkbManagedBlockEditor.Upsert(
            bridge.Content ?? string.Empty,
            metadata.ProjectInstallationId,
            metadata.PublicVariantId,
            stagedBridgeBlock.Content!,
            existing?.BridgeBlockSha256);
        if (!bridgeEdit.Success)
        {
            return Failed(bridgeEdit.Diagnostics);
        }

        var registryEdit = XkbRegistryDocumentMerger.Upsert(
            registry.Content,
            metadata,
            existing?.RegistryEntrySha256);
        if (!registryEdit.Success)
        {
            return Failed(registryEdit.Diagnostics);
        }

        var operations = new List<XkbInstallOperation>();
        AddWrite(operations, paths, central, centralContent);
        AddWrite(operations, paths, bridge, bridgeEdit.Content!);
        AddWrite(operations, paths, registry, registryEdit.Content!);

        var installation = new XkbInstalledVariant(
            metadata.ProjectInstallationId,
            metadata.BaseLayoutId,
            metadata.BaseVariantId,
            metadata.ResolvedBaseSectionId,
            metadata.PublicVariantId,
            metadata.InternalSectionId,
            metadata.Description,
            centralBlockHash,
            bridgeEdit.ManagedBlockSha256!,
            registryEdit.EntrySha256!,
            existing?.InstalledAtUtc ?? verifiedAtUtc,
            verifiedAtUtc,
            toolVersion);
        var installations = manifest.Installations
            .Where(item => !string.Equals(
                item.ProjectInstallationId,
                metadata.ProjectInstallationId,
                StringComparison.Ordinal))
            .Append(installation)
            .OrderBy(item => item.ProjectInstallationId, StringComparer.Ordinal)
            .ToArray();
        var files = UpdateFileRecords(
            manifest.Files,
            [
                (CentralPath, centralContent, centralCreated),
                (bridgePath, bridgeEdit.Content!, ExistingCreated(manifest, bridgePath, !bridge.Exists)),
                (RegistryPath, registryEdit.Content!, ExistingCreated(manifest, RegistryPath, !registry.Exists))
            ]);
        var updatedManifest = new XkbInstallationManifest(
            XkbInstallationManifest.CurrentSchemaVersion,
            installations,
            files);

        return Succeeded(
            existing is null ? XkbInstallAction.Install : XkbInstallAction.Update,
            metadata.ProjectInstallationId,
            paths,
            operations,
            updatedManifest);
    }

    public static XkbInstallPlanResult PlanUninstall(
        string projectInstallationId,
        XdgDirectoryPaths paths,
        XkbInstallationManifest manifest,
        IReadOnlyList<XkbInstallFileSnapshot> currentFiles)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(projectInstallationId);
        ArgumentNullException.ThrowIfNull(paths);
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentNullException.ThrowIfNull(currentFiles);

        var diagnostics = ValidateInputs(paths, manifest, currentFiles);
        if (diagnostics.Count > 0)
        {
            return Failed(diagnostics);
        }

        var installed = manifest.Installations.SingleOrDefault(item =>
            string.Equals(item.ProjectInstallationId, projectInstallationId, StringComparison.Ordinal));
        if (installed is null)
        {
            diagnostics.Add(new XkbDiagnostic("KSP005", "The selected project is not installed."));
            return Failed(diagnostics);
        }

        var metadata = new XkbUserVariantMetadata(
            installed.ProjectInstallationId,
            installed.BaseLayoutId,
            installed.BaseVariantId,
            installed.ResolvedBaseSectionId,
            installed.PublicVariantId,
            installed.Description);
        var snapshots = currentFiles.ToDictionary(file => file.RelativePath, StringComparer.Ordinal);
        var central = Snapshot(snapshots, CentralPath);
        var bridgePath = $"symbols/{installed.BaseLayoutId}";
        var bridge = Snapshot(snapshots, bridgePath);
        var registry = Snapshot(snapshots, RegistryPath);
        if (!central.Exists || !bridge.Exists || !registry.Exists ||
            central.IsSymbolicLink || bridge.IsSymbolicLink || registry.IsSymbolicLink)
        {
            diagnostics.Add(new XkbDiagnostic(
                "KSP003",
                "An installed destination is missing or is a symbolic link."));
            return Failed(diagnostics);
        }

        var centralRecord = manifest.Files.SingleOrDefault(file =>
            string.Equals(file.RelativePath, CentralPath, StringComparison.Ordinal));
        if (centralRecord is null ||
            !central.Content!.StartsWith(CentralHeader, StringComparison.Ordinal) ||
            !string.Equals(Hash(central.Content), centralRecord.Sha256, StringComparison.Ordinal))
        {
            diagnostics.Add(new XkbDiagnostic(
                "KSP004",
                "symbols/keyboardstudio was changed outside KeyboardStudio."));
            return Failed(diagnostics);
        }

        var centralEdit = XkbManagedBlockEditor.Remove(
            central.Content,
            projectInstallationId,
            installed.CentralBlockSha256);
        var bridgeEdit = XkbManagedBlockEditor.Remove(
            bridge.Content!,
            projectInstallationId,
            installed.BridgeBlockSha256);
        var registryEdit = XkbRegistryDocumentMerger.Remove(
            registry.Content!,
            metadata,
            installed.RegistryEntrySha256);
        if (!centralEdit.Success || !bridgeEdit.Success || !registryEdit.Success)
        {
            return Failed(
                centralEdit.Diagnostics.Concat(bridgeEdit.Diagnostics).Concat(registryEdit.Diagnostics).ToArray());
        }

        var operations = new List<XkbInstallOperation>();
        var remainingInstallations = manifest.Installations
            .Where(item => !string.Equals(item.ProjectInstallationId, projectInstallationId, StringComparison.Ordinal))
            .ToArray();
        AddRemovalOrWrite(
            operations,
            paths,
            central,
            remainingInstallations.Length == 0 ? null : centralEdit.Content,
            deleteWhenEmpty: remainingInstallations.Length == 0 && centralRecord.WasCreatedByKeyboardStudio);
        AddRemovalOrWrite(
            operations,
            paths,
            bridge,
            bridgeEdit.Content,
            deleteWhenEmpty: ExistingCreated(manifest, bridgePath, fallback: false));
        AddRemovalOrWrite(
            operations,
            paths,
            registry,
            registryEdit.Content,
            deleteWhenEmpty: ExistingCreated(manifest, RegistryPath, fallback: false));

        var changedContent = operations
            .Where(operation => operation.Kind != XkbInstallOperationKind.Delete)
            .ToDictionary(
                operation => operation.RelativePath,
                operation => operation.Content!,
                StringComparer.Ordinal);
        var deleted = operations
            .Where(operation => operation.Kind == XkbInstallOperationKind.Delete)
            .Select(operation => operation.RelativePath)
            .ToHashSet(StringComparer.Ordinal);
        var files = manifest.Files
            .Where(file => !deleted.Contains(file.RelativePath))
            .Select(file => changedContent.TryGetValue(file.RelativePath, out var content)
                ? file with { Sha256 = Hash(content) }
                : file)
            .ToArray();
        var updatedManifest = new XkbInstallationManifest(
            XkbInstallationManifest.CurrentSchemaVersion,
            remainingInstallations,
            files);

        return Succeeded(
            XkbInstallAction.Uninstall,
            projectInstallationId,
            paths,
            operations,
            updatedManifest);
    }

    private static List<XkbDiagnostic> ValidateInputs(
        XdgDirectoryPaths paths,
        XkbInstallationManifest manifest,
        IReadOnlyList<XkbInstallFileSnapshot> currentFiles)
    {
        var diagnostics = new List<XkbDiagnostic>();
        try
        {
            _ = XkbInstallationManifestSerializer.Serialize(manifest);
        }
        catch (InvalidDataException exception)
        {
            diagnostics.Add(new XkbDiagnostic("KSP001", exception.Message));
        }

        if (!XdgDirectoryPathValidator.IsSafe(paths))
        {
            diagnostics.Add(new XkbDiagnostic("KSP003", "The resolved XDG paths are unsafe."));
        }

        if (currentFiles.Select(file => file.RelativePath)
            .Distinct(StringComparer.Ordinal).Count() != currentFiles.Count)
        {
            diagnostics.Add(new XkbDiagnostic("KSP001", "A current file snapshot occurs more than once."));
        }

        return diagnostics;
    }

    private static XkbInstallFileSnapshot Snapshot(
        Dictionary<string, XkbInstallFileSnapshot> snapshots,
        string relativePath) =>
        snapshots.TryGetValue(relativePath, out var snapshot)
            ? snapshot
            : new XkbInstallFileSnapshot(relativePath, Content: null, IsSymbolicLink: false);

    private static void AddWrite(
        List<XkbInstallOperation> operations,
        XdgDirectoryPaths paths,
        XkbInstallFileSnapshot current,
        string content)
    {
        if (string.Equals(current.Content, content, StringComparison.Ordinal))
        {
            return;
        }

        operations.Add(new XkbInstallOperation(
            current.Exists ? XkbInstallOperationKind.Replace : XkbInstallOperationKind.Create,
            current.RelativePath,
            Destination(paths, current.RelativePath),
            current.Content is null ? null : Hash(current.Content),
            content,
            Hash(content)));
    }

    private static void AddRemovalOrWrite(
        List<XkbInstallOperation> operations,
        XdgDirectoryPaths paths,
        XkbInstallFileSnapshot current,
        string? content,
        bool deleteWhenEmpty)
    {
        if (content is null && deleteWhenEmpty)
        {
            operations.Add(new XkbInstallOperation(
                XkbInstallOperationKind.Delete,
                current.RelativePath,
                Destination(paths, current.RelativePath),
                Hash(current.Content!),
                Content: null,
                ContentSha256: null));
            return;
        }

        var replacement = content ?? string.Empty;
        AddWrite(operations, paths, current, replacement);
    }

    private static string Destination(XdgDirectoryPaths paths, string relativePath)
    {
        var destination = Path.GetFullPath(Path.Combine(
            [paths.UserXkbRoot, .. relativePath.Split('/')]));
        if (!destination.StartsWith(
                paths.UserXkbRoot + Path.DirectorySeparatorChar,
                StringComparison.Ordinal))
        {
            throw new InvalidDataException("An install destination escapes the user XKB root.");
        }

        return destination;
    }

    private static XkbManagedFileRecord[] UpdateFileRecords(
        IReadOnlyList<XkbManagedFileRecord> existing,
        IReadOnlyList<(string Path, string Content, bool Created)> changed)
    {
        var updates = changed.ToDictionary(item => item.Path, StringComparer.Ordinal);
        return existing
            .Where(file => !updates.ContainsKey(file.RelativePath))
            .Concat(changed.Select(item => new XkbManagedFileRecord(
                item.Path,
                Hash(item.Content),
                item.Created)))
            .OrderBy(file => file.RelativePath, StringComparer.Ordinal)
            .ToArray();
    }

    private static bool ExistingCreated(
        XkbInstallationManifest manifest,
        string path,
        bool fallback) =>
        manifest.Files.SingleOrDefault(file => string.Equals(
            file.RelativePath,
            path,
            StringComparison.Ordinal))?.WasCreatedByKeyboardStudio ?? fallback;

    private static string Hash(string content) =>
        Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(content)));

    private static XkbInstallPlanResult Succeeded(
        XkbInstallAction action,
        string projectInstallationId,
        XdgDirectoryPaths paths,
        IReadOnlyList<XkbInstallOperation> operations,
        XkbInstallationManifest manifest) =>
        new(
            true,
            new XkbInstallPlan(
                action,
                projectInstallationId,
                operations,
                manifest,
                Path.Combine(paths.KeyboardStudioStateRoot, "installations.json")),
            []);

    private static XkbInstallPlanResult Failed(IReadOnlyList<XkbDiagnostic> diagnostics) =>
        new(false, null, diagnostics);
}
