<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\KeyboardStudio.Core\KeyboardStudio.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../templates/seeds/us-basic.kbdproj"
                      LogicalName="KeyboardStudio.Persistence.SeedProjects.us-basic.kbdproj" />
  </ItemGroup>
</Project>
